# Use postgres/example user/password credentials
version: "3.9"

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: test_db
    ports: -"5432:5432"

  adminer:
    image: dpage/pgadmin4
    restart: always
    ports:
      - 8080:8080
    environment:
      PGADMIN_DEFAULT_EMAIL: example@gmail.com
      PGADMIN_DEFAULT_PASSWORD: password
